#!/bin/sh
##
## Linux-CryptHome: Mount an encrypted user's home directory at login
## Copyright (c) 2016-2017 SATOH Fumiyasu @ OSS Technology Corp., Japan
##
## License: GNU General Public License version 3
##

set -u
export PATH="/bin:/usr/bin:/sbin:/usr/sbin"

atexit() {
  rc="$?"
  [ -n "${key_id+set}" ] && keyctl revoke "$key_id"
  exit "$rc"
}

unset key_id
trap atexit EXIT

## ======================================================================

uid="$1"; shift

key_name="${CRYPTHOME_KEY_NAME:-crypthome:$uid}"
pwent=$(getent passwd "$uid") || exit $?
name="${pwent%%:*}"
home=$(echo "$pwent" |sed 's/^.*:\([^:]*\):[^:]*$/\1/')
[ -n "$name" ] && [ -n "$home" ] || exit $?

device_crypted=$(
  lvs \
    --noheadings \
    --options lv_name,lv_path \
  |awk \
    -v name="crypthome.$name" \
    '$1==name {print $2}' \
  ;
)
[ -n "$device_crypted" ] || exit 0

device_decrypted_name="decrypthome.$name.$uid.$(basename "$(realpath "$device_crypted")")"
device_decrypted="/dev/mapper/$device_decrypted_name"

if cryptsetup status "$device_decrypted_name" >/dev/null 2>&1; then
  exit 0
fi

key_id=$(keyctl request user "$key_name") || exit $?

keyctl \
  pipe \
  "$key_id" \
|cryptsetup \
  open \
  "$device_crypted" \
  "$device_decrypted_name" \
  --key-file - \
|| exit $?

mount "$device_decrypted" "$home" || exit $?

exit 0
