#!/bin/sh
##
## Linux-CryptHome: Mount an encrypted user's home directory at login
##
## SPDX-FileCopyrightText: 2017-2025 SATOH Fumiyasu @ OSSTech Corp., Japan
## SPDX-License-Identifier: GPL-3.0-or-later
##

set -u
export PATH="/usr/bin:/usr/sbin"

uid="$1"

pwent=$(getent passwd "$uid") || exit $?
home=$(echo "$pwent" |sed 's/^.*:\([^:]*\):[^:]*$/\1/')
[ -n "$home" ] || exit $?
device=$(awk -v home="$home" '$2==home {print $1}' /proc/mounts)
[ -n "$device" ] || exit 0

umount "$home" || exit $?
cryptsetup close "$device" || exit $?

exit 0
