#!/bin/sh
##
## Linux-CryptHome: Mount an encrypted user's home directory at login
## Copyright (c) 2016-2017 SATOH Fumiyasu @ OSS Technology Corp., Japan
##
## License: GNU General Public License version 3
##

set -u
export PATH="/bin:/usr/bin:/sbin:/usr/sbin"

if [ x"$(id -u)" != x"0" ]; then
  exit 0
fi

uid=$(id -u "$PAM_USER") || exit $?

key_name="${CRYPTHOME_KEY_NAME:-crypthome:$uid}"
key_ring="${CRYPTHOME_KEY_RING:-@u}"

case "$PAM_TYPE" in
auth)
  keyctl padd user "$key_name" "$key_ring" || exit $?
  ## FIXME: Set key expiry
  if [ x"$key_ring" = x"@s" ]; then
    "${0%/*}/crypthome-mount" "$uid" || exit $?
  fi
  systemctl enable "crypthome@$uid.service" || exit $?
  ;;
#open_session)
#  systemctl start "crypthome@$uid.service" || exit $?
#  ;;
#close_session)
#  # Do NOT systemctl stop "crypthome@$uid.service" || exit $?
#  ;;
esac

exit 0
